-- DDL/DML Script for SQLite3 database to be used by the website prototype
-- Author: Deep Bhattacharya
-- Date: 30-SEP-2015

/* Table to hold the various CDF types that the web site will support
Possible values may be XSD, JSON Schema, ... (others can be added in the future)
*/

-- DDL
CREATE TABLE CANONICAL_FORMATS (CDF_TYPE_ID INTEGER PRIMARY KEY AUTOINCREMENT, CDF_TYPE VARCHAR(25) NOT NULL);

-- DML
INSERT INTO CANONICAL_FORMATS (CDF_TYPE) VALUES ('XSD');
INSERT INTO CANONICAL_FORMATS (CDF_TYPE) VALUES ('JSON_SCHEMA');

/* Table to hold the CDF list
*/

-- DDL
CREATE TABLE CANONICALS (CDF_ID INTEGER PRIMARY KEY AUTOINCREMENT, CDF_NAME VARCHAR(25) NOT NULL, CDF_WIKI_RELATIVE_PATH VARCHAR(100));

-- DML
INSERT INTO CANONICALS (CDF_NAME, CDF_WIKI_RELATIVE_PATH) VALUES ('ARTICLE', 'Files/Article');
INSERT INTO CANONICALS (CDF_NAME, CDF_WIKI_RELATIVE_PATH) VALUES ('EMPLOYEE', 'Files/Employee');

/* Table to hold the schemas
One CDF can have multiple schemas e.g. XSD and JSON Schema
*/

-- DDL
CREATE TABLE CANONICAL_SCHEMAS (CDF_SCHEMA_ID INTEGER PRIMARY KEY AUTOINCREMENT, FOREIGN KEY (CDF_ID) REFERENCES CANONICALS(CDF_ID) NOT NULL, FOREIGN KEY (CDF_TYPE_ID) REFERENCES CANONICAL_FORMATS(CDF_TYPE_ID) NOT NULL, CDF_VERSION VARCHAR(5) DEFAULT '0.1', CDF_SCHEMA_RELATIVE_PATH VARCHAR(100) NOT NULL);

-- DML
INSERT INTO CANONICAL_SCHEMAS (CDF_ID, CDF_TYPE_ID, CDF_VERSION, CDF_SCHEMA_RELATIVE_PATH) VALUES ((SELECT CDF_ID FROM CANONICALS WHERE CDF_NAME = 'ARTICLE'), (SELECT CDF_TYPE_ID FROM CANONICAL_FORMATS WHERE CDF_TYPE = 'XSD'), '1.0', 'Files/Article/V1.0/Article.xsd');
INSERT INTO CANONICAL_SCHEMAS (CDF_ID, CDF_TYPE_ID, CDF_VERSION, CDF_SCHEMA_RELATIVE_PATH) VALUES ((SELECT CDF_ID FROM CANONICALS WHERE CDF_NAME = 'EMPLOYEE'), (SELECT CDF_TYPE_ID FROM CANONICAL_FORMATS WHERE CDF_TYPE = 'XSD'), '1.0', 'Files/Employee/V1.0/Article.xsd');