-- DDL/DML Script for SQLite3 database to be used by the website prototype
-- Author: Deep Bhattacharya
-- Date: 30-SEP-2015

/* Table to hold the various CDF types that the web site will support
Possible values may be XSD, JSON Schema, ... (others can be added in the future)
*/

-- DDL
CREATE TABLE CANONICAL_FORMATS (CDF_TYPE_ID INTEGER PRIMARY KEY AUTOINCREMENT, CDF_TYPE VARCHAR(25) NOT NULL);

-- DML
INSERT INTO TABLE CANONICAL_FORMATS (CDF_TYPE) VALUES ('XSD');
INSERT INTO TABLE CANONICAL_FORMATS (CDF_TYPE) VALUES ('JSON Schema');

/* Table to hold the CDF list
*/

-- DDL
CREATE TABLE CANONICALS (CDF_ID INTEGER PRIMARY KEY AUTOINCREMENT, CDF_NAME VARCHAR(25) NOT NULL, CDF_VERSION VARCHAR(5) DEFAULT '0.1', CDF_WIKI_RELATIVE_PATH VARCHAR(100));

-- DML
INSERT INTO TABLE CANONICALS (CDF_NAME, CDF_WIKI_RELATIVE_PATH) VALUES ('ARTICLE', 'Files/Article');
INSERT INTO TABLE CANONICALS (CDF_NAME, CDF_WIKI_RELATIVE_PATH) VALUES ('EMPLOYEE', 'Files/Employee');

/* Table to hold the schemas
One CDF can have multiple schemas e.g. XSD and JSON Schema
*/

-- DDL
CREATE TABLE CANONICAL_SCHEMAS (CDF_SCHEMA_ID INTEGER PRIMARY KEY AUTOINCREMENT, FOREIGN KEY (CDF_NAME) REFERENCES CANONICALS(CDF_NAME) NOT NULL, FOREIGN KEY (CDF_TYPE) REFERENCES CANONICAL_FORMATS(CDF_TYPE) NOT NULL, CDF_SCHEMA_PATH VARCHAR(100) NOT NULL);

-- DML
INSERT INTO TABLE CANONICAL_SCHEMAS (CDF_NAME, CDF_TYPE, CDF_SCHEMA_PATH) VALUES ('ARTICLE', 'XSD', 'Files/Article/Article.xsd');
INSERT INTO TABLE CANONICAL_SCHEMAS (CDF_NAME, CDF_TYPE, CDF_SCHEMA_PATH) VALUES ('ARTICLE', 'XSD', 'Files/Employee/Employee.xsd');